### ISSUE TITLE
Please create release tags

### ISSUE THREAD

**Issue by amishHammer** [JasonCarter80/concord232#1]
There is no release tag that matches the release in pypi.

Please make release tags and or upload tar.gz's to pypi for OS packagers to use.

**Comment by JasonCarter80** [comment]
I see it right here:  https://pypi.python.org/pypi?:action=files&name=concord232&version=0.14

**Comment by amishHammer** [comment]
1) There is no release tag here https://github.com/JasonCarter80/concord232/releases that matches the 0.14 release in pypi. How am I supposed to tell what is and isn't in that release when comparing it to master in git?

2) There is no tar or zip file in pypi. I am making operating system native packages for this code (think apt-get install concord232) which can not be made using the wheel files as I need access to the setup.py which is not bundled in it. 

3) Not creating release tags is extremely poor SCM foo

**Comment by rwa** [comment]
v0.15 release tag created
