### ISSUE TITLE
Add [Arm|Disarm] [Silent] [Away|Stay]

### ISSUE THREAD

**Issue by lehighkid** [JasonCarter80/concord232#3]
First - thank you for this code - I have it working very well as intended - great job!

Would it be possible to add to the code to accept parameters for silent (5 key press) via the client for arming and disarming to away or stay states?  

Use case - arming and disarming while still inside in the evening and mornings

**Comment by rwa** [comment]
I am trying to get this to work, but have not had any success.

I'm not sure if this is a software issue or not. But I am able to successfully send single keypresses like "2" for arm stay, but not the sequence 5,2 for arm stay silent. The panel does not seem to acknowledge the message. I have checked what is being sent, and it appears to conform to the protocol:

06 40 01 00 05 02 4E

Length, keypress cmd, partition #, area #, keypress1, keypress 2, checksum

Does anyone have any insight into this problem?

**Comment by rwa** [comment]
I finally figured this out.  The correct sequence for silent stay is:

06 40 01 00 05 21 6D

You need keypress 0x21 rather than 0x02 for the arm to stay.  I don't know why.  The protocal manual says this is the "keyfob arm" key.

**Comment by rwa** [comment]
PR#4 implemented arming silent to stay.

I'm working on a new PR which updates the API to match the interface of the Concord a little better - and also allows either the silent or instant options to be available when arming to stay or away.

**Comment by rwa** [comment]
Fixed in PR #5 .
